Repository stanleyowen/loofi, pull requests merged in 2021-09, with the labels that each got.

#61 feat: add desktop application support
  .gitignore
  package.json
  public/electron.js
  yarn.lock
Labels: enhancement, dependencies

#59 Improved Search Feature
  .gitignore
  package.json
  src/components/base.component.tsx
  src/components/home.component.tsx
  src/components/search.component.tsx
  yarn.lock
Labels: enhancement

#63 Improved Accessibility
  package.json
  src/App.css
  src/components/navbar.component.tsx
  src/components/sidebar.component.tsx
  yarn.lock
Labels: ui/ux

#67 Merge `next` branch from `master` branch
  .gitignore
  package.json
  public/electron.js
  yarn.lock
Labels: dependencies

#68 Version 0.2.1
  .gitignore
  package.json
  src/App.css
  src/components/base.component.tsx
  src/components/home.component.tsx
  src/components/navbar.component.tsx
  src/components/search.component.tsx
  src/components/sidebar.component.tsx
  yarn.lock
Labels: enhancement, ui/ux, dependencies

#71 Improved Skeleton Preview
  README.md
  package.json
  src/components/home.component.tsx
  src/components/search.component.tsx
  yarn.lock
Labels: enhancement

#73 Improved Skeleton Preview
  README.md
  package.json
  src/components/home.component.tsx
  src/components/search.component.tsx
  yarn.lock
Labels: enhancement, dependencies

#75 Improve Beta Configuration Settings
  .env
  package.json
  src/components/sidebar.component.tsx
  yarn.lock
Labels: enhancement

#77 Codebase: Improve Code Quality
  .env
  package.json
  src/components/home.component.tsx
  yarn.lock
Labels: enhancement, dependencies

#79 Codebase: Improve Performance
  README.md
  package.json
  public/electron.js
  public/index.html
  src/App.tsx
  src/components/app.component.tsx
  src/components/base.component.tsx
  src/components/home.component.tsx
  src/components/search.component.tsx
  src/components/sidebar.component.tsx
  yarn.lock
Labels: enhancement

#81 Display Message when Client get Disconnected from Server
  package.json
  src/App.css
  src/components/about.component.tsx
  src/components/app.component.tsx
  yarn.lock
Labels: enhancement, dependencies

#84 Move `switchTab` to child element and Improve Documentation
  Privacy.md
  src/components/about.component.tsx
  src/components/sidebar.component.tsx
Labels: documentation, enhancement

#88 Added Verification Method for Google Search Console
  public/google14f52748d0656c83.html
  public/index.html
Labels: enhancement

#86 Improve Layout
  package.json
  src/App.css
  yarn.lock
Labels: ui/ux, dependencies

#89 Version 0.2.5
  .env
  Privacy.md
  README.md
  package.json
  public/electron.js
  public/index.html
  src/App.css
  src/App.tsx
  src/components/about.component.tsx
  src/components/app.component.tsx
  src/components/base.component.tsx
  src/components/home.component.tsx
  src/components/search.component.tsx
  src/components/sidebar.component.tsx
  yarn.lock
Labels: enhancement, ui/ux, dependencies

#92 Migrate `@material-ui` to `@mui` Dependency for `v5`
  package.json
  public/electron.js
  src/App.css
  src/components/about.component.tsx
  src/components/app.component.tsx
  src/components/home.component.tsx
  src/components/navbar.component.tsx
  src/components/search.component.tsx
  src/components/sidebar.component.tsx
  yarn.lock
Labels: dependencies

#95 Improve App Design
  package.json
  src/App.css
  src/components/controls.component.tsx
  src/components/navbar.component.tsx
  src/components/search.component.tsx
  src/components/sidebar.component.tsx
  src/lib/icons.component.tsx
  yarn.lock
Labels: ui/ux, dependencies

#99 Reduce desktop installer size
  package.json
  scripts/postbuild.js
  scripts/prebuild.js
  src/components/controls.component.tsx
Labels: enhancement, dependencies

#100 Add Skip Music Feature
  package.json
  src/components/controls.component.tsx
  yarn.lock
Labels: enhancement

#104 Version 0.3.7
  package.json
  public/electron.js
  scripts/postbuild.js
  scripts/prebuild.js
  src/App.css
  src/components/about.component.tsx
  src/components/app.component.tsx
  src/components/controls.component.tsx
  src/components/home.component.tsx
  src/components/navbar.component.tsx
  src/components/search.component.tsx
  src/components/sidebar.component.tsx
  src/lib/icons.component.tsx
  yarn.lock
Labels: enhancement, ui/ux, dependencies

#108 Add Theme Feature
  package.json
  src/components/about.component.tsx
  src/img/a9d4d30d6b483ee638a0dddab5bb047e.webp
  src/img/d14c82db65be85a729c042492447dc5d.webp
  src/lib/icons.component.tsx
  yarn.lock
Labels: enhancement

#110 Improve App Layout
  package.json
  src/App.css
  src/components/about.component.tsx
  src/lib/icons.component.tsx
Labels: ui/ux

#115 Improve Codebase Quality
  package.json
  src/components/app.component.tsx
  src/components/home.component.tsx
  src/components/navbar.component.tsx
  src/components/search.component.tsx
  src/components/sidebar.component.tsx
  yarn.lock
Labels: dependencies, codebase quality

#117 Version 0.4.5
  package.json
  src/App.css
  src/components/about.component.tsx
  src/components/app.component.tsx
  src/components/home.component.tsx
  src/components/navbar.component.tsx
  src/components/search.component.tsx
  src/components/sidebar.component.tsx
  src/img/a9d4d30d6b483ee638a0dddab5bb047e.webp
  src/img/d14c82db65be85a729c042492447dc5d.webp
  src/lib/icons.component.tsx
  yarn.lock
Labels: enhancement, dependencies, codebase quality
