Repository stanleyowen/loofi, pull requests merged in 2021-06, with the labels that each got.

#3 Added Home Feature
  .gitignore
  client/.gitignore
  client/public/index.html
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/components/app.component.js
  client/src/components/base.component.js
  client/src/components/sidebar.component.js
  client/src/reportWebVitals.js
Labels: enhancement, ui/ux

#4 Added Controller Feature
  client/src/App.css
  client/src/components/app.component.js
  client/src/components/controls.component.js
  client/src/lib/icons.component.js
Labels: enhancement, ui/ux

#6 Refactor code
  .gitignore
  README.md
  client/package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.test.js
  src/App.tsx
  src/components/app.component.tsx
  src/components/base.component.tsx
  src/components/controls.component.tsx
  src/components/navbar.component.tsx
  src/components/sidebar.component.tsx
  src/index.tsx
  src/lib/icons.component.tsx
  src/logo.svg
  src/react-app-env.d.ts
  src/reportWebVitals.js
  src/setupTests.js
  tsconfig.json
  yarn.lock
Labels: enhancement

#7 Switching Components Between Tabs
  src/App.css
  src/components/base.component.tsx
  src/components/controls.component.tsx
  src/components/home.component.tsx
  src/components/navbar.component.tsx
  src/components/search.component.tsx
  src/components/sidebar.component.tsx
Labels: enhancement, ui/ux

#8 Load Images from Local
  .gitignore
  src/App.css
  src/img/aaddc3454ccbefbb2d8d8461f8f7f481.webp
  src/img/d229bbf31eaeebc7c88897732d8b932d.webp
Labels: ui/ux

#9 Added Large Card Album
  package.json
  src/App.css
  src/App.tsx
  src/components/app.component.tsx
  src/components/home.component.tsx
  src/components/sidebar.component.tsx
  yarn.lock
Labels: ui/ux

#11 Fixed Error in Compiling
  package.json
  src/components/app.component.tsx
  src/components/sidebar.component.tsx
  yarn.lock
Labels: enhancement

#12 Improved Navbar Functionality
  src/App.css
  src/App.tsx
  src/components/app.component.tsx
  src/components/navbar.component.tsx
  src/components/sidebar.component.tsx
Labels: ui/ux

#13 Added Ability to Stream Music in Controller Component
  src/App.css
  src/components/controls.component.tsx
  src/components/sidebar.component.tsx
Labels: approved, enhancement
