Repository stanleyowen/loofi, pull requests merged in 2021-10, with the labels that each got.

#121 Improve Settings Preview
  package.json
  src/App.css
  src/components/about.component.tsx
  src/components/base.component.tsx
  src/components/preferences.component.tsx
  src/components/settings.component.tsx
  src/components/sidebar.component.tsx
  src/img/a9d4d30d6b483ee638a0dddab5bb047e.webp
  src/img/aaddc3454ccbefbb2d8d8461f8f7f481.webp
  src/img/d14c82db65be85a729c042492447dc5d.webp
  src/img/d229bbf31eaeebc7c88897732d8b932d.webp
  src/lib/icons.component.tsx
  src/lib/theme.json
Labels: enhancement, ui/ux, codebase quality

#125 Improve Issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: documentation, enhancement, hacktoberfest-accepted

#126 Version 0.6.4
  package.json
  src/App.css
  src/components/about.component.tsx
  src/components/base.component.tsx
  src/components/preferences.component.tsx
  src/components/settings.component.tsx
  src/components/sidebar.component.tsx
  src/img/a9d4d30d6b483ee638a0dddab5bb047e.webp
  src/img/aaddc3454ccbefbb2d8d8461f8f7f481.webp
  src/img/d14c82db65be85a729c042492447dc5d.webp
  src/img/d229bbf31eaeebc7c88897732d8b932d.webp
  src/lib/icons.component.tsx
  src/lib/theme.json
Labels: documentation, enhancement, ui/ux, dependencies, codebase quality

#128 Improve Copy Button Preview
  package.json
  src/components/about.component.tsx
  src/lib/icons.component.tsx
  yarn.lock
Labels: ui/ux

#130 Fixed `Lint` Error
  src/App.tsx
  src/components/about.component.tsx
  src/components/app.component.tsx
  src/components/base.component.tsx
  src/components/controls.component.tsx
  src/components/home.component.tsx
  src/components/navbar.component.tsx
  src/components/preferences.component.tsx
  src/components/search.component.tsx
  src/components/settings.component.tsx
  src/components/sidebar.component.tsx
  src/lib/icons.component.tsx
Labels: dependencies, ongoing, codebase quality

#129 feat(ci): Add eslint
  .eslintrc.yml
  .github/workflows/lint.yml
  package.json
  src/App.tsx
  src/components/about.component.tsx
  src/components/app.component.tsx
  src/components/base.component.tsx
  src/components/controls.component.tsx
  src/components/home.component.tsx
  src/components/navbar.component.tsx
  src/components/preferences.component.tsx
  src/components/search.component.tsx
  src/components/settings.component.tsx
  src/components/sidebar.component.tsx
  src/lib/icons.component.tsx
  yarn.lock
Labels: enhancement, dependencies

#132 Improve Theme Layout
  package.json
  src/components/preferences.component.tsx
  src/lib/icons.component.tsx
  yarn.lock
Labels: ui/ux, dependencies, ongoing

#135 Save Tab History
  package.json
  src/App.tsx
Labels: enhancement, ui/ux
